version: "3.10"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createcachetable && python /docking/manage.py runserver 0.0.0.0:8000"
    container_name: docking
    
    ports:
      - 8000:8000
  
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
#   postgres_data: